type BotEventType = 1007 | 1015 | 1052 | 1071 | 1061 | 1068 | 1088;

const RELOCATE_SUCCESS_EVENT: BotEventType = 1071;
const RELOCATE_FAILED_EVENT: BotEventType = 1088;
const RELOCATE_FAILED_RETURN_TO_CHARGE_EVENT: BotEventType = 1068;
const MOP_INSTALLED_EVENT: BotEventType = 1007;
const CHANGE_MOP_REMINDER_EVENT: BotEventType = 1052;
// 1061 ??

export {
  BotEventType,
  RELOCATE_SUCCESS_EVENT,
  RELOCATE_FAILED_RETURN_TO_CHARGE_EVENT,
  MOP_INSTALLED_EVENT,
  CHANGE_MOP_REMINDER_EVENT,
  RELOCATE_FAILED_EVENT,
};
