type BotEventType = 1007 | 1015 | 1052 | 1071 | 1088;

const RELOCATE_SUCCESS_EVENT: BotEventType = 1071;
const RELOCATE_FAILED_EVENT: BotEventType = 1088;
const MOP_INSTALLED_EVENT: BotEventType = 1007;
const CHANGE_MOP_REMINDER_EVENT: BotEventType = 1052;

export { RELOCATE_SUCCESS_EVENT, MOP_INSTALLED_EVENT, CHANGE_MOP_REMINDER_EVENT, RELOCATE_FAILED_EVENT };
