CREATE TABLE IF NOT EXISTS bot_events (
    id int PRIMARY KEY AUTO_INCREMENT,
    evt_code INT NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bot_errors (
    id int PRIMARY KEY AUTO_INCREMENT,
    error_code INT NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);